# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy wordpress theme to Azure Web App - tsvcountrymusic-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Put repo contents into theme subfolder
      run: |
        args=()
        for f in *;do args+="${f} ";done
        mkdir -p ${{ vars.WP_THEME_PATH }}
        mv $args ${{ vars.WP_THEME_PATH }}
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ vars.AZURE_APP_NAME }}'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
